import Link from "next/link";
import {
  Video,
  ListChecks,
  Sparkles,
  FileBarChart,
  Mail,
  ArrowRight,
  CheckCircle2,
} from "lucide-react";

const features = [
  {
    icon: Video,
    title: "Live Video Interviews",
    body: "HR + candidate join an ultra-low latency WebRTC room powered by LiveKit. Candidates join directly via secure link with zero friction.",
  },
  {
    icon: ListChecks,
    title: "Guided Question Flow",
    body: "Work through customized interview question rubrics, mark questions asked or skipped, and capture timestamped notes in real time.",
  },
  {
    icon: Sparkles,
    title: "AI Follow-Up Prompts",
    body: "After each candidate answer, get dynamic, insightful follow-up questions autonomously generated by open LLMs (Groq Llama-3).",
  },
  {
    icon: FileBarChart,
    title: "Structured Score Reports",
    body: "Objective candidate evaluation with quantitative scores, detailed AI rationale, and instantly shareable decision reports.",
  },
];

export default function Home() {
  return (
    <main className="min-h-screen">
      {/* Hero Section */}
      <section className="mx-auto max-w-4xl px-6 pb-20 pt-12 sm:pt-16 text-center">
        <div className="inline-flex items-center gap-2 rounded-full bg-brand-50 px-3.5 py-1 text-xs font-semibold text-brand-700 border border-brand-200/70 mb-6">
          <Sparkles className="w-3.5 h-3.5 text-brand-600" />
          <span>Next-Generation AI Video Interviewing</span>
        </div>

        <h1 className="text-balance text-4xl font-bold tracking-tight text-slate-900 sm:text-6xl sm:leading-[1.15]">
          AI-assisted video interviews,
          <br />
          <span className="text-brand-600">from first hello to hire.</span>
        </h1>

        <p className="mx-auto mt-6 max-w-2xl text-pretty text-base sm:text-lg text-slate-600 leading-relaxed">
          Run streamlined candidate interviews with live WebRTC video, real-time
          speech transcription, intelligent AI follow-ups, and automated
          evaluation scoring rubrics.
        </p>

        <div className="mt-10 flex flex-wrap justify-center items-center gap-3.5">
          <Link
            href="/signup"
            className="inline-flex items-center gap-2 rounded-full bg-brand-600 hover:bg-brand-700 text-white px-7 py-3 text-sm font-semibold transition-all shadow-md shadow-brand-600/20 hover:shadow-lg"
          >
            <span>Start Interviewing Free</span>
            <ArrowRight className="w-4 h-4" />
          </Link>
          <Link
            href="#features"
            className="inline-flex items-center gap-2 rounded-full bg-white hover:bg-slate-100 text-slate-700 border border-slate-200 px-6 py-3 text-sm font-semibold transition-all shadow-sm"
          >
            <span>Explore Platform</span>
          </Link>
        </div>
      </section>

      {/* Features Section */}
      <section id="features" className="scroll-mt-24 mx-auto max-w-5xl px-6 py-16">
        <div className="text-center mb-12">
          <p className="text-xs font-semibold uppercase tracking-[0.2em] text-brand-600">
            Platform Capabilities
          </p>
          <h2 className="mt-2 text-3xl font-bold tracking-tight text-slate-900">
            Intelligent Interview Technology
          </h2>
          <p className="mt-2 text-slate-600 text-sm max-w-lg mx-auto">
            Everything your talent team needs to assess candidates objectively, thoroughly, and efficiently.
          </p>
        </div>

        <div className="grid gap-6 sm:grid-cols-2">
          {features.map((f) => (
            <div
              key={f.title}
              className="rounded-3xl border border-slate-200/80 bg-white p-7 shadow-sm hover:shadow-md transition-all"
            >
              <div className="w-10 h-10 rounded-2xl bg-brand-50 flex items-center justify-center text-brand-600 mb-4">
                <f.icon className="h-5 w-5" />
              </div>
              <h3 className="text-lg font-semibold text-slate-900">{f.title}</h3>
              <p className="mt-2 text-sm text-slate-600 leading-relaxed">{f.body}</p>
            </div>
          ))}
        </div>
      </section>

      {/* About Us Section */}
      <section id="about" className="scroll-mt-24 mx-auto max-w-5xl px-6 py-16">
        <div className="rounded-3xl border border-slate-200/80 bg-white p-8 sm:p-12 shadow-sm">
          <div className="max-w-2xl">
            <p className="text-xs font-semibold uppercase tracking-[0.2em] text-brand-600">
              About Grevya
            </p>
            <h2 className="mt-2 text-3xl font-bold tracking-tight text-slate-900">
              Empowering Hiring Teams with Transparent AI
            </h2>
            <p className="mt-4 text-slate-600 text-sm sm:text-base leading-relaxed">
              Grevya AI Interviewer is dedicated to eliminating hiring biases and
              streamlining recruitment through ethical, transparent AI assistance.
              Built on open-source standards, our platform keeps candidates engaged,
              evaluates skills accurately, and empowers decision makers with unbiased data.
            </p>
            <div className="mt-6 flex flex-wrap gap-4 text-xs font-medium text-slate-700">
              <div className="flex items-center gap-1.5 rounded-full bg-slate-100 px-3 py-1">
                <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                <span>Zero Candidate Friction</span>
              </div>
              <div className="flex items-center gap-1.5 rounded-full bg-slate-100 px-3 py-1">
                <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                <span>Open-Source LLM Architecture</span>
              </div>
              <div className="flex items-center gap-1.5 rounded-full bg-slate-100 px-3 py-1">
                <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                <span>Standardized Rubrics</span>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Contact Section */}
      <section id="contact" className="scroll-mt-24 mx-auto max-w-4xl px-6 py-16 text-center">
        <div className="rounded-3xl border border-slate-200/80 bg-white p-8 sm:p-12 shadow-sm">
          <div className="w-12 h-12 rounded-2xl bg-brand-50 flex items-center justify-center text-brand-600 mx-auto mb-4">
            <Mail className="h-6 w-6" />
          </div>
          <h2 className="text-2xl sm:text-3xl font-bold text-slate-900">
            Get in Touch with the Grevya Team
          </h2>
          <p className="mt-3 text-slate-600 text-sm max-w-md mx-auto">
            Have questions about self-hosting, custom question rubrics, or enterprise integrations? We are here to help.
          </p>
          <div className="mt-6 flex flex-wrap justify-center gap-3">
            <a
              href="mailto:contact@grevya.ai"
              className="inline-flex items-center gap-2 rounded-full bg-brand-600 hover:bg-brand-700 text-white px-6 py-2.5 text-xs font-semibold transition-colors shadow-sm"
            >
              <Mail className="w-3.5 h-3.5" />
              <span>contact@grevya.ai</span>
            </a>
            <Link
              href="/signup"
              className="inline-flex items-center gap-2 rounded-full bg-slate-100 hover:bg-slate-200 text-slate-800 px-6 py-2.5 text-xs font-semibold transition-colors"
            >
              <span>Create Free Account</span>
            </Link>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-slate-200 py-10 text-center text-xs text-slate-500">
        <p>© {new Date().getFullYear()} Grevya AI Interviewer. All rights reserved.</p>
      </footer>
    </main>
  );
}
